-- DailyLog central notification bus
-- Run once in Supabase SQL Editor.
-- Receiver users must be members of the same workspace.
-- Only workspace roles 'owner' and 'admin' may publish.

create table if not exists public.notification_events (
    id bigint generated by default as identity primary key,
    workspace_id uuid not null,
    source text not null default '',
    title text not null,
    message text not null,
    notification_type text not null default 'info',
    created_by uuid not null default auth.uid(),
    created_at timestamptz not null default now()
);

create index if not exists ix_notification_events_workspace_id_id
on public.notification_events(workspace_id, id);

alter table public.notification_events enable row level security;

drop policy if exists "notification_events_select_members" on public.notification_events;
create policy "notification_events_select_members"
on public.notification_events
for select
to authenticated
using (
    exists (
        select 1
        from public.workspace_members wm
        where wm.workspace_id = notification_events.workspace_id
          and wm.user_id = auth.uid()
    )
);

drop policy if exists "notification_events_insert_admins" on public.notification_events;
create policy "notification_events_insert_admins"
on public.notification_events
for insert
to authenticated
with check (
    created_by = auth.uid()
    and exists (
        select 1
        from public.workspace_members wm
        where wm.workspace_id = notification_events.workspace_id
          and wm.user_id = auth.uid()
          and lower(coalesce(wm.role, '')) in ('owner', 'admin')
    )
);

-- Intentionally no UPDATE or DELETE policy for client applications.
-- Old events can be cleaned up manually/server-side if needed.

select id, workspace_id, source, title, created_at
from public.notification_events
order by id desc
limit 20;
